version: '3'

services:
  node:
    container_name: node_backend
    image: lib_quality_node
    ports:
      - ${APP_PORT}:5000
    depends_on:
      - postgres

  postgres:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: