version: '3'

services:
  node:
    container_name: node_backend
    image: lib_quality_node
    ports:
      - ${APP_PORT}:5000
    depends_on:
      - postgres
    restart: always

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres-data:
    external: true